### ISSUE TITLE
Link on Activation email does not work

### ISSUE THREAD

**Issue by sgangoly** [artiste-qb-net/BayesForge#2]
Hi Robert,

The link sent for activation does not find "the server". Hence the Discourse login does not work.

I am a great enthusiast of QC, ML and AI and have been for the last 15 odd years. Hence my interest as I am getting into programming the same and am also a newbie enthusiast into TensorFlow.  Been a member of IBM qlab for a while now and have started to dabble in Rigetti's pyquil as well.

Hence my interest in your setups :-)

Thanks and best regards

Santanu

**Comment by rrtucci** [comment]
Thanks Santanu. Sorry for the bug.  We are aware of it. We will fix it soon. A temporary fix is to replace the prefix ip address from

http://34.239.105.70/...
To
http://52.6.214.124/...

**Comment by sgangoly** [comment]
Hi Robert,
Awesome! That works ! :-)

Many thanks for that!

Best Regards
Santanu
